require( foreign )
source( 'ssgm.R' )

load_data_and_subgroups <- function( name, targetclass=NA ) {
    basedir <- '../exp'
    
    ## load subgroup list
    dirname <- list.files( basedir, name )
    if ( length(dirname) > 1 ) {
        stop( 'matches more than one file name' )
    }
    sgfn <- list.files( sprintf( '%s/%s', basedir, dirname ), '^stats1' )
    sgfn <- sprintf( '%s/%s/%s', basedir, dirname, sgfn )

    cat( 'loading subgroup descriptor list from', sgfn, '\n' )
    sg    <- read.table( sgfn, sep=';', fileEncoding='latin1', header=FALSE, skip=1 )
    names(sg) <- c('id', 'idx_in', 'idx_out', 'orig_quality', 'size', 'num_cond', 'description')
    sg <- sg[ order( sg$idx_in ), ]
    sg$description <- as.character( sg$description )
    sg$description <- gsub( ' && ', ' & ', sg$description )
    sg$description <- gsub( ' = ', ' == ', sg$description )
    sg$description <- gsub( '([a-z])-([a-z])', '\\1_\\2', sg$description )
    
    ## load target var name
    infofile  <- list.files(sprintf( '%s/datasets', basedir ),
                            sprintf( '%s.emm', name ))
    infofile  <- read.table(sprintf( '%s/datasets/%s', basedir, infofile ),
                           sep = '=', fileEncoding='latin1', strip.white=TRUE)
    targetname <- as.character(infofile$V2[2])

    ## load data
    datafile <- list.files(sprintf( '%s/datasets', basedir ),
                           sprintf( '%s.arff', name ))
    data     <- read.arff( sprintf( '%s/datasets/%s', basedir, datafile ) )

    ## replace dashes with underscores
    names(data) <- gsub( '([a-z])-([a-z])', '\\1_\\2', names(data) )
    
    ## just in case apply same transformation to target variable name
    targetname   <- gsub( '([a-z])-([a-z])', '\\1_\\2', targetname )
    
    ## replace factor conditions without quotes (in lists produced by matthijs)
    ## with ones where quotes exist
    fcond <- get_factor_conditions( data )
    print( fcond )
    if ( nrow(fcond) > 0 ) {
        for ( i in 1:nrow(fcond) ) {
            cat( 'replacing', fcond[i,1], 'with', fcond[i,2], '\n' )
            regexstr <- sprintf( '%s |%s$', fcond[i,1], fcond[i,1] )
            sg$description <- gsub( regexstr, fcond[i,2], sg$description )
        }
    }

    ## finally, transform target to use same label that Matthijs did
    ## the name parameter must be given manually!!!!!
    if ( !is.na(targetclass) ) {
        newtarget <- rep( 0, nrow(data) )
        newtarget[ data[,targetname] == targetclass ] <- 1
        data[, targetname] <- newtarget
    }

    ## recompute qualities, at this point we have already converted
    ## a factor target to a numeric one, if there was one.
    qfnc <- get_quality_effsize( data, targetname, targetclass=NA )
    C    <- cover_matrix( sg$description, data )
    sg$quality <- apply( C, 2, function(S) qfnc(S==1) )

    ## in some cases the descriptions in the results files seem to contain
    ## broken rules, i.e. things that return an empty set.
    ## for those rules quality will be NaN.
    nans <- is.nan( sg$quality )
    if ( any( nans ) ) {
        sg <- sg[!nans, ]
        C  <- C[, !nans]
    }
    
    list( D=data, mr=sg, targetname=targetname, C=C )
}

## if the subgroup descriptors do not have quotes around factor values
## we must insert such quotes in appropriate places.
## this is because R expects conditions on factor variables
## be given as Varname == 'value', where 'value' must be in quotes.
## the data frame generated by this function has two columns,
## where there is a quote-free version of a factor condition in the 1st column,
## and a variant of the same condition including quotes in the 2nd column.
get_factor_conditions <- function( data ) {
    src_conditions    <- c()
    target_conditions <- c()
    varnames <- names(data)
    for ( vn in varnames ) {
        if ( class( data[,vn] ) == 'factor' ) {
            for ( lvl in levels( data[,vn] ) ) {
                src_conditions    <- c( src_conditions, sprintf( '%s == %s', vn, lvl ) )
                target_conditions <- c( target_conditions, sprintf( "%s == '%s'", vn, lvl ) )
            }
        }
    }
    data.frame( src=src_conditions, target=target_conditions, stringsAsFactors=FALSE )
}
